/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIForms;

import DataDriver.DictionaryData;
import dilexis.Combinator;
import dilexis.WordsAdder;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JSeparator;

/**
 *
 * @author Comarch
 */
public class Learning extends javax.swing.JPanel {
    
    GridBagLayout layout = new GridBagLayout();
    CombinePanel cmb;
    
    public static boolean isWordStockOpened = false;
    public static boolean isSettingsOpened = false;
    public static ArrayList<JLabel> words = new ArrayList<JLabel>();
    public static ArrayList<JLabel> translations = new ArrayList<JLabel>();
    public static ArrayList<JSeparator> separators = new ArrayList<JSeparator>();
    static JLabel editedWord;

    /**
     * Creates new form Learning
     */
    public Learning() {
        initComponents();
    jComboBox3.setVisible(false);
    wordEditor.setVisible(false);
        
    words.add(w1);
    words.add(w2);
    words.add(w3);
    words.add(w4);
    words.add(w5);
    words.add(w6);
    words.add(w7);
    words.add(w8);
    words.add(w9);
    words.add(w10);
    
        translations.add(t1);
    translations.add(t2);
    translations.add(t3);
    translations.add(t4);
    translations.add(t5);
    translations.add(t6);
    translations.add(t7);
    translations.add(t8);
    translations.add(t9);
    translations.add(t10);
    
        t1.setVisible(false);    
        w1.setVisible(false);     
        t2.setVisible(false);
        w2.setVisible(false);
        t3.setVisible(false);
        w3.setVisible(false);
        t4.setVisible(false);
        w4.setVisible(false);
        t5.setVisible(false);
        w5.setVisible(false);
        t6.setVisible(false);
        w6.setVisible(false);
        t7.setVisible(false);
        w7.setVisible(false);
        t8.setVisible(false);
        w8.setVisible(false);
        t9.setVisible(false);
        w9.setVisible(false);
        t10.setVisible(false);
        w10.setVisible(false);
        
        s1.setVisible(false);
        separators.add(s1);
        
        s2.setVisible(false);
        separators.add(s2);
        
        s3.setVisible(false);
        separators.add(s3);
        
        s4.setVisible(false);
        separators.add(s4);
        
        s5.setVisible(false);
        separators.add(s5);
        
        s6.setVisible(false);
        separators.add(s6);
        
        s7.setVisible(false);
        separators.add(s7);
        
        s8.setVisible(false);
        separators.add(s8);
        
        s9.setVisible(false);
        separators.add(s9);
        
        s10.setVisible(false);
        separators.add(s10);
        
        s11.setVisible(false);
        separators.add(s11);
    }

    public static void getWordsFromLabels(){
    words.add(w1);
    words.add(w2);
    words.add(w3);
    words.add(w4);
    words.add(w5);
    words.add(w6);
    words.add(w7);
    words.add(w8);
    words.add(w9);
    words.add(w10);
    
    translations.add(t1);
    translations.add(t2);
    translations.add(t3);
    translations.add(t4);
    translations.add(t5);
    translations.add(t6);
    translations.add(t7);
    translations.add(t8);
    translations.add(t9);
    translations.add(t10);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        w1 = new javax.swing.JLabel();
        s2 = new javax.swing.JSeparator();
        t2 = new javax.swing.JLabel();
        w2 = new javax.swing.JLabel();
        s3 = new javax.swing.JSeparator();
        t3 = new javax.swing.JLabel();
        w3 = new javax.swing.JLabel();
        s4 = new javax.swing.JSeparator();
        t4 = new javax.swing.JLabel();
        w4 = new javax.swing.JLabel();
        s5 = new javax.swing.JSeparator();
        s6 = new javax.swing.JSeparator();
        t5 = new javax.swing.JLabel();
        w5 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        wordEditor = new javax.swing.JPanel();
        editField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        s1 = new javax.swing.JSeparator();
        t8 = new javax.swing.JLabel();
        w8 = new javax.swing.JLabel();
        s9 = new javax.swing.JSeparator();
        t9 = new javax.swing.JLabel();
        w9 = new javax.swing.JLabel();
        s10 = new javax.swing.JSeparator();
        s11 = new javax.swing.JSeparator();
        t10 = new javax.swing.JLabel();
        w10 = new javax.swing.JLabel();
        t6 = new javax.swing.JLabel();
        w6 = new javax.swing.JLabel();
        s7 = new javax.swing.JSeparator();
        t7 = new javax.swing.JLabel();
        w7 = new javax.swing.JLabel();
        s8 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(242, 253, 253));
        setFocusable(false);
        setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(992, 681));
        setMinimumSize(new java.awt.Dimension(992, 681));
        setPreferredSize(new java.awt.Dimension(992, 681));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Foreign words:");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(109, 73, 109));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Translation:");

        t1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        t1.setForeground(new java.awt.Color(109, 73, 109));
        t1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t1.setText("Translation1");
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });

        w1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        w1.setForeground(new java.awt.Color(0, 102, 153));
        w1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        w1.setText("Word1");
        w1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                w1MouseEntered(evt);
            }
        });

        s2.setBackground(new java.awt.Color(192, 239, 239));
        s2.setForeground(new java.awt.Color(192, 239, 239));

        t2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        t2.setForeground(new java.awt.Color(109, 73, 109));
        t2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t2.setText("Translation2");
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2MouseClicked(evt);
            }
        });

        w2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        w2.setForeground(new java.awt.Color(0, 102, 153));
        w2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        w2.setText("Word2");
        w2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w2MouseClicked(evt);
            }
        });

        s3.setBackground(new java.awt.Color(192, 239, 239));
        s3.setForeground(new java.awt.Color(192, 239, 239));

        t3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        t3.setForeground(new java.awt.Color(109, 73, 109));
        t3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t3.setText("Translation3");
        t3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t3MouseClicked(evt);
            }
        });

        w3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        w3.setForeground(new java.awt.Color(0, 102, 153));
        w3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        w3.setText("Word3");
        w3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w3MouseClicked(evt);
            }
        });

        s4.setBackground(new java.awt.Color(192, 239, 239));
        s4.setForeground(new java.awt.Color(192, 239, 239));

        t4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        t4.setForeground(new java.awt.Color(109, 73, 109));
        t4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t4.setText("Translation4");
        t4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t4MouseClicked(evt);
            }
        });

        w4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        w4.setForeground(new java.awt.Color(0, 102, 153));
        w4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        w4.setText("Word4");
        w4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w4MouseClicked(evt);
            }
        });

        s5.setBackground(new java.awt.Color(192, 239, 239));
        s5.setForeground(new java.awt.Color(192, 239, 239));

        s6.setBackground(new java.awt.Color(192, 239, 239));
        s6.setForeground(new java.awt.Color(192, 239, 239));

        t5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        t5.setForeground(new java.awt.Color(109, 73, 109));
        t5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t5.setText("Translation5");
        t5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t5MouseClicked(evt);
            }
        });

        w5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        w5.setForeground(new java.awt.Color(0, 102, 153));
        w5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        w5.setText("Word5");
        w5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w5MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(180, 197, 204));

        jComboBox1.setBackground(new java.awt.Color(227, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Write & Learn", "Popular words" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.setFocusable(false);
        jComboBox1.setOpaque(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jButton1.setText("Define the words");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setOpaque(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("How many words?");

        jComboBox2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "5" }));
        jComboBox2.setFocusable(false);

        jButton2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Go!");
        jButton2.setFocusable(false);
        jButton2.setOpaque(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Clear");
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.setOpaque(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jComboBox3.setBackground(new java.awt.Color(227, 255, 255));
        jComboBox3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Top 300 words", "Top 100 words", "Top 100 verbs", "Top 100 nouns", "Top 100 adjectives" }));
        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox3.setFocusable(false);
        jComboBox3.setOpaque(false);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 151, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        wordEditor.setBackground(new java.awt.Color(242, 253, 253));

        editField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jButton3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton3.setText("Save");
        jButton3.setOpaque(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout wordEditorLayout = new javax.swing.GroupLayout(wordEditor);
        wordEditor.setLayout(wordEditorLayout);
        wordEditorLayout.setHorizontalGroup(
            wordEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wordEditorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        wordEditorLayout.setVerticalGroup(
            wordEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(editField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        s1.setBackground(new java.awt.Color(94, 178, 178));
        s1.setForeground(new java.awt.Color(94, 178, 178));

        t8.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        t8.setForeground(new java.awt.Color(109, 73, 109));
        t8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t8.setText("Translation8");
        t8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t8MouseClicked(evt);
            }
        });

        w8.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        w8.setForeground(new java.awt.Color(0, 102, 153));
        w8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        w8.setText("Word8");
        w8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w8MouseClicked(evt);
            }
        });

        s9.setBackground(new java.awt.Color(192, 239, 239));
        s9.setForeground(new java.awt.Color(192, 239, 239));

        t9.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        t9.setForeground(new java.awt.Color(109, 73, 109));
        t9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t9.setText("Translation9");
        t9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t9MouseClicked(evt);
            }
        });

        w9.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        w9.setForeground(new java.awt.Color(0, 102, 153));
        w9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        w9.setText("Word9");
        w9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w9MouseClicked(evt);
            }
        });

        s10.setBackground(new java.awt.Color(192, 239, 239));
        s10.setForeground(new java.awt.Color(192, 239, 239));

        s11.setBackground(new java.awt.Color(192, 239, 239));
        s11.setForeground(new java.awt.Color(192, 239, 239));

        t10.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        t10.setForeground(new java.awt.Color(109, 73, 109));
        t10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t10.setText("Translation10");
        t10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t10MouseClicked(evt);
            }
        });

        w10.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        w10.setForeground(new java.awt.Color(0, 102, 153));
        w10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        w10.setText("Word10");
        w10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w10MouseClicked(evt);
            }
        });

        t6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        t6.setForeground(new java.awt.Color(109, 73, 109));
        t6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t6.setText("Translation6");
        t6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t6MouseClicked(evt);
            }
        });

        w6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        w6.setForeground(new java.awt.Color(0, 102, 153));
        w6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        w6.setText("Word6");
        w6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                w6MouseEntered(evt);
            }
        });

        s7.setBackground(new java.awt.Color(192, 239, 239));
        s7.setForeground(new java.awt.Color(192, 239, 239));

        t7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        t7.setForeground(new java.awt.Color(109, 73, 109));
        t7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t7.setText("Translation7");
        t7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t7MouseClicked(evt);
            }
        });

        w7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        w7.setForeground(new java.awt.Color(0, 102, 153));
        w7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        w7.setText("Word7");
        w7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w7MouseClicked(evt);
            }
        });

        s8.setBackground(new java.awt.Color(192, 239, 239));
        s8.setForeground(new java.awt.Color(192, 239, 239));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(wordEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(s6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(w5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(s4, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(w3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(s3, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(w2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(w1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(w4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(s11)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(w10, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(s10, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(s9, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(w8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(s8, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(w7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(s7, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(w6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(w9, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w1)
                    .addComponent(t1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w2)
                    .addComponent(t2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w3)
                    .addComponent(t3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w4)
                    .addComponent(t4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w5)
                    .addComponent(t5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w6)
                    .addComponent(t6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w7)
                    .addComponent(t7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w8)
                    .addComponent(t8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w9)
                    .addComponent(t9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w10)
                    .addComponent(t10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wordEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedItem().toString().equals("Write & Learn")) {
            jButton1.setText("Define the words");
            jComboBox3.setVisible(false);
        } else {
        jButton1.setText("Load the words");
        jComboBox3.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        WordsAdder.cleanWords(words, translations, separators);
        if (jComboBox1.getSelectedItem().toString().equals("Write & Learn") && isWordStockOpened == false) {
          WordsWriter.start();
        }
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void w1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w1MouseEntered
    // TODO add your handling code here:
    }//GEN-LAST:event_w1MouseEntered

    private void w1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w1MouseClicked
    wordEditor.setVisible(true);
    editField.setText(w1.getText());
    editField.requestFocusInWindow();
    editField.selectAll();
    editedWord = w1;
    }//GEN-LAST:event_w1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (editField.getText().equals("")) {
           jButton3.setForeground(Color.red);
        } else {  
            jButton3.setForeground(Color.black);
            editedWord.setText(editField.getText());
            editField.setText("");
            wordEditor.setVisible(false);}
    }//GEN-LAST:event_jButton3MouseClicked

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
    wordEditor.setVisible(true);
    editField.setText(t1.getText()); 
    editField.requestFocusInWindow();
    editField.selectAll();
    editedWord = t1;        // TODO add your handling code here:
    }//GEN-LAST:event_t1MouseClicked

    private void w2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w2MouseClicked
    wordEditor.setVisible(true);
    editField.setText(w2.getText()); 
    editField.requestFocusInWindow();
    editField.selectAll();
    editedWord = w2;        // TODO add your handling code here:
    }//GEN-LAST:event_w2MouseClicked

    private void t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseClicked
    wordEditor.setVisible(true);
    editField.setText(t2.getText()); 
    editField.requestFocusInWindow();
    editField.selectAll();
    editedWord = t2;        // TODO add your handling code here:
    }//GEN-LAST:event_t2MouseClicked

    private void w3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w3MouseClicked
    wordEditor.setVisible(true);
    editField.setText(w3.getText()); 
    editField.requestFocusInWindow();
    editField.selectAll();
    editedWord = w3;        // TODO add your handling code here:
    }//GEN-LAST:event_w3MouseClicked

    private void t3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t3MouseClicked
    wordEditor.setVisible(true);
    editField.setText(t3.getText()); 
    editField.requestFocusInWindow();
    editField.selectAll();
    editedWord = t3;        // TODO add your handling code here:
    }//GEN-LAST:event_t3MouseClicked

    private void w4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w4MouseClicked
    wordEditor.setVisible(true);
    editField.setText(w4.getText()); 
    editField.requestFocusInWindow();
    editField.selectAll();
    editedWord = w4;        // TODO add your handling code here:
    }//GEN-LAST:event_w4MouseClicked

    private void t4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t4MouseClicked
    wordEditor.setVisible(true);
    editField.setText(t4.getText()); 
    editField.requestFocusInWindow();
    editField.selectAll();
    editedWord = t4;        // TODO add your handling code here:
    }//GEN-LAST:event_t4MouseClicked

    private void w5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w5MouseClicked
    wordEditor.setVisible(true);
    editField.setText(w5.getText()); 
    editField.requestFocusInWindow();
    editField.selectAll();
    editedWord = w5;        // TODO add your handling code here:
    }//GEN-LAST:event_w5MouseClicked

    private void t5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t5MouseClicked
    wordEditor.setVisible(true);
    editField.setText(t5.getText()); 
    editField.requestFocusInWindow();
    editField.selectAll();
    editedWord = t5;        // TODO add your handling code here:
    }//GEN-LAST:event_t5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
    WordsAdder.cleanWords(words, translations, separators);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (!w1.isVisible()) {}else{
            cmb = new CombinePanel();
        MainForm.jPanel1.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        MainForm.jPanel1.add(cmb, c);
        cmb.setVisible(false);
        DictionaryData.insertWords(words, translations);
        Combinator.loadWordsToList(words, translations);
        //WordsAdder.cleanWords(words, translations, separators);
        cmb.setVisible(true);
        jPanel1.setEnabled(false);
        jPanel1.setVisible(false);
        wordEditor.setEnabled(false);
        wordEditor.setVisible(false);
        setVisible(false);
        setEnabled(false);
        MainForm.jButton2.setVisible(false);
        MainForm.jButton3.setVisible(false);
        CombinePanel.stageCounter = 0;
        
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked
    public static void qqq(JLabel jLabel){
    jLabel.setText(w1.getText());
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_t8MouseClicked

    private void w8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_w8MouseClicked

    private void t9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_t9MouseClicked

    private void w9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_w9MouseClicked

    private void t10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_t10MouseClicked

    private void w10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_w10MouseClicked

    private void t6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_t6MouseClicked

    private void w6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_w6MouseClicked

    private void w6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_w6MouseEntered

    private void t7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_t7MouseClicked

    private void w7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_w7MouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    public static javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JSeparator s1;
    public static javax.swing.JSeparator s10;
    public static javax.swing.JSeparator s11;
    public static javax.swing.JSeparator s2;
    public static javax.swing.JSeparator s3;
    public static javax.swing.JSeparator s4;
    public static javax.swing.JSeparator s5;
    public static javax.swing.JSeparator s6;
    public static javax.swing.JSeparator s7;
    public static javax.swing.JSeparator s8;
    public static javax.swing.JSeparator s9;
    public static javax.swing.JLabel t1;
    public static javax.swing.JLabel t10;
    public static javax.swing.JLabel t2;
    public static javax.swing.JLabel t3;
    public static javax.swing.JLabel t4;
    public static javax.swing.JLabel t5;
    public static javax.swing.JLabel t6;
    public static javax.swing.JLabel t7;
    public static javax.swing.JLabel t8;
    public static javax.swing.JLabel t9;
    public static javax.swing.JLabel w1;
    public static javax.swing.JLabel w10;
    public static javax.swing.JLabel w2;
    public static javax.swing.JLabel w3;
    public static javax.swing.JLabel w4;
    public static javax.swing.JLabel w5;
    public static javax.swing.JLabel w6;
    public static javax.swing.JLabel w7;
    public static javax.swing.JLabel w8;
    public static javax.swing.JLabel w9;
    public static javax.swing.JPanel wordEditor;
    // End of variables declaration//GEN-END:variables
}
