/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIForms;

import dilexis.WordsAdder;

/**
 *
 * @author Comarch
 */
public class WordsWriter extends javax.swing.JDialog {
 
    public static int counter = 0;
    /**
     * Creates new form WordsWriter
     */
    public WordsWriter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        count2.setText(Learning.jComboBox2.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        count1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        count2 = new javax.swing.JLabel();
        translation = new javax.swing.JLabel();
        wordField = new javax.swing.JTextField();
        word = new javax.swing.JLabel();
        translationField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 70, 100));

        count1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        count1.setForeground(new java.awt.Color(255, 102, 102));
        count1.setText("0");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("/");

        count2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        count2.setForeground(new java.awt.Color(255, 102, 102));

        translation.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        translation.setForeground(new java.awt.Color(183, 237, 237));
        translation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        translation.setText("Translation:");

        wordField.setNextFocusableComponent(translationField);
        wordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                wordFieldFocusGained(evt);
            }
        });

        word.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        word.setForeground(new java.awt.Color(175, 214, 234));
        word.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        word.setText("Word:");

        translationField.setNextFocusableComponent(jButton1);
        translationField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                translationFieldFocusGained(evt);
            }
        });
        translationField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                translationFieldKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Vrinda", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Add");
        jButton1.setFocusPainted(false);
        jButton1.setNextFocusableComponent(wordField);
        jButton1.setOpaque(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(word, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(translation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(translationField)
                            .addComponent(wordField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(count1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(count2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(count1)
                    .addComponent(jLabel1)
                    .addComponent(count2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(word, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(translation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(translationField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (wordField.getText().equals("")) {
        } else if (translationField.getText().equals("")) {
        } else{
        if(Learning.jComboBox2.getSelectedItem().toString().equals("5")){
                    WordsAdder.addWords(Learning.words, Learning.translations, Learning.separators, wordField, translationField, counter);
                  counter++;
                  String counterString = ""+counter;
                  count1.setText(counterString); 
                  translationField.setText("");
                  wordField.requestFocus();
        if (counter == 5) {
            Learning.separators.get(counter).setVisible(true);
            dispose();
            counter = 0;
        }
    } else if (Learning.jComboBox2.getSelectedItem().toString().equals("10")) {
           WordsAdder.addWords(Learning.words, Learning.translations, Learning.separators, wordField, translationField, counter);
                counter++;
                String counterString = ""+counter;
                count1.setText(counterString);
                translationField.setText("");
                wordField.requestFocus();
        if (counter == 10) {
            Learning.separators.get(counter).setVisible(true);
            dispose();
            counter = 0;
        } 
        }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void wordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_wordFieldFocusGained
    wordField.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_wordFieldFocusGained

    private void translationFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_translationFieldFocusGained
    translationField.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_translationFieldFocusGained

    private void translationFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_translationFieldKeyPressed
if (wordField.getText().equals("")) {       
        } else if (translationField.getText().equals("")) {
        } else{
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
      if(Learning.jComboBox2.getSelectedItem().toString().equals("5")){
      WordsAdder.addWords(Learning.words, Learning.translations, Learning.separators, wordField, translationField, counter);
                counter++;
                String counterString = ""+counter;
                count1.setText(counterString);
                translationField.setText("");
                wordField.requestFocus();
        if (counter == 5) {
            Learning.separators.get(counter).setVisible(true);
            dispose();
            counter = 0;
        }
    } else if (Learning.jComboBox2.getSelectedItem().toString().equals("10")) {
           WordsAdder.addWords(Learning.words, Learning.translations, Learning.separators, wordField, translationField, counter);
                counter++;
                String counterString = ""+counter;
                count1.setText(counterString);
                translationField.setText("");
                wordField.requestFocus();
        if (counter == 10) {
            Learning.separators.get(counter).setVisible(true);
            dispose();
            counter = 0;
        } 
        }
     }  }      // TODO add your handling code here:
    }//GEN-LAST:event_translationFieldKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    WordsAdder.cleanWords(Learning.words, Learning.translations, Learning.separators);
    counter = 0;// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordsWriter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordsWriter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordsWriter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordsWriter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WordsWriter dialog = new WordsWriter(new javax.swing.JFrame(), true);
               
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel count1;
    public static javax.swing.JLabel count2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel translation;
    public javax.swing.JTextField translationField;
    private javax.swing.JLabel word;
    public javax.swing.JTextField wordField;
    // End of variables declaration//GEN-END:variables
}
